# Generated by Django 5.2.8 on 2025-11-16 02:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('billetera', 'Billetera'), ('cuenta_bancaria', 'Cuenta bancaria'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('token', models.CharField(help_text='Token del gateway', max_length=255, verbose_name='Token')),
                ('ultimos4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('es_predeterminado', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('metadatos', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['-es_predeterminado', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
                ('simbolo', models.CharField(blank=True, max_length=5, verbose_name='Símbolo')),
                ('decimales', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales')),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('categoria', models.CharField(blank=True, choices=[('retail', 'Retail'), ('streaming', 'Streaming'), ('software', 'Software'), ('educacion', 'Educación'), ('otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_proveedores/', verbose_name='Logo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del plan')),
                ('duracion_dias', models.PositiveIntegerField(help_text='Duración en días (ej. 30 para mensual, 365 para anual)', verbose_name='Duración (días)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.moneda', verbose_name='Moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='suscripciones.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['proveedor__nombre', 'precio'],
                'unique_together': {('proveedor', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('renovacion_automatica', models.BooleanField(default=False, verbose_name='Renovación automática')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Motivo o detalles de la suscripción', null=True, verbose_name='Descripción')),
                ('id_externo', models.CharField(blank=True, help_text='ID en el gateway externo', max_length=255, null=True, verbose_name='ID externo')),
                ('metadatos', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.moneda', verbose_name='Moneda')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.plan', verbose_name='Plan')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=8, help_text='Tasa usada para conversión', max_digits=18, null=True, verbose_name='Tasa de cambio')),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('referencia', models.CharField(blank=True, help_text='ID de transacción', max_length=255, null=True, verbose_name='Referencia')),
                ('respuesta_gateway', models.JSONField(blank=True, null=True, verbose_name='Respuesta del gateway')),
                ('pagado_en', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suscripciones.metodopago', verbose_name='Método de pago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.moneda', verbose_name='Moneda')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_vencimiento', 'Recordatorio de vencimiento'), ('pago_fallido', 'Pago fallido'), ('pago_exitoso', 'Pago exitoso'), ('manual', 'Manual')], max_length=50, verbose_name='Tipo')),
                ('enviar_en', models.DateTimeField(verbose_name='Enviar en')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('datos', models.JSONField(blank=True, help_text='Datos para plantilla', null=True, verbose_name='Datos')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='suscripciones.suscripcion', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-enviar_en'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('metadatos', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='suscripciones.suscripcion', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['estado'], name='suscripcion_estado_694884_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['fecha_fin'], name='suscripcion_fecha_f_0ad475_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['referencia'], name='suscripcion_referen_33b4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='suscripcion_estado_d967de_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['enviar_en'], name='suscripcion_enviar__890d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['enviado_en'], name='suscripcion_enviado_18cceb_idx'),
        ),
    ]
