# Generated by Django 5.2.8 on 2025-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='suscripcion',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='token',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='id_externo',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
