# Generated by Django 5.2.8 on 2025-11-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_remove_pago_metodo_pago_remove_pago_moneda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='metadatos',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='metadatos',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='metadatos',
        ),
    ]
